const users = [
  {
    userId: "1",
    name: "Alice",
    email: "alice@mail.com",
    password: "111111",
    avatar:
      "https://fastly.picsum.photos/id/1064/200/200.jpg?hmac=xUH-ovzKEHg51S8vchfOZNAOcHB6b1TI_HzthmqvcWU",
  },
  {
    userId: "2",
    name: "Bob",
    email: "bob@mail.com",
    password: "222222",
    avatar:
      "https://fastly.picsum.photos/id/625/200/200.jpg?hmac=oIwf4IzbglfXYZo-9VXZTHju2-ox3D-Vooeuioav_nw",
  },
  {
    userId: "3",
    name: "Charlie",
    email: "charlie@mail.com",
    password: "333333",
    avatar:
      "https://fastly.picsum.photos/id/90/200/200.jpg?hmac=zltjAmHceKvUbRnvGycGPocNMsLFu-jiTwBEcre1_pU",
  },
  {
    userId: "4",
    name: "Diana",
    email: "diana@mail.com",
    password: "444444",
    avatar:
      "https://fastly.picsum.photos/id/912/200/200.jpg?hmac=tYYyMFni6bya5yEVkwmmFekjWGedHVByLtPI5q1lcyw",
  },
  {
    userId: "5",
    name: "Eve",
    email: "eve@mail.com",
    password: "555555",
    avatar:
      "https://fastly.picsum.photos/id/423/200/200.jpg?hmac=fXwRSSVHFlYgq9MfObWaWCb_p9L6ysOWda9lLOtAWc0",
  },
];

const stories = [
  {
    storyId: "1",
    userId: "1",
    title: "The Enchanted Forest",
    body: "Deep in the heart of the forest, where sunlight filters through the canopy, lies a realm of magic and wonder. Ancient trees stand as sentinels, their gnarled roots entwined with secrets of old. Creatures of myth and legend roam freely, their presence felt in every rustle of leaves and whisper of wind. Here, among the shadows and dappled light, adventures unfold and destinies are forged.",
    tags: ["fantasy", "adventure"],
    views: 1000,
    upvotes: 100,
    downvotes: 10,
    date: "2022-12-06",
  },
  {
    storyId: "2",
    userId: "1",
    title: "Lost in Time",
    body: "A mysterious portal opened before them, a shimmering gateway to worlds unknown. With trepidation and excitement, they stepped across the threshold, leaving behind the familiar confines of their own time. As they journeyed through the corridors of time, they encountered civilizations long forgotten, witnessed the rise and fall of empires, and unraveled the mysteries of existence itself.",
    tags: ["time-travel", "mystery"],
    views: 2000,
    upvotes: 200,
    downvotes: 20,
    date: "2022-11-14",
  },
  {
    storyId: "3",
    userId: "1",
    title: "The Secret Garden",
    body: "Behind the old mansion, there was a hidden paradise, a lush oasis untouched by time. Vibrant blooms danced in the gentle breeze, their perfume filling the air with sweet fragrance. Twisting vines and verdant foliage obscured paths that led deeper into the garden's heart, where mysteries awaited discovery and dreams came to life.",
    tags: ["mystery", "nature"],
    views: 3000,
    upvotes: 300,
    downvotes: 30,
    date: "2022-10-29",
  },
  {
    storyId: "4",
    userId: "1",
    title: "Beyond the Stars",
    body: "In a distant galaxy, where the light of a thousand suns paints the heavens in hues of violet and gold, a great adventure unfolds. Across vast expanses of space, starships glide like silent phantoms, their crews bound by destiny and fueled by hope. Amidst the cosmic tapestry of worlds and wonders, heroes rise to challenge the darkness and embrace the infinite possibilities of the cosmos.",
    tags: ["space", "sci-fi"],
    views: 4000,
    upvotes: 400,
    downvotes: 40,
    date: "2023-09-10",
  },
  {
    storyId: "5",
    userId: "1",
    title: "The Legend of the Phoenix",
    body: "In ancient times...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["legend", "mythology"],
    views: 5000,
    upvotes: 500,
    downvotes: 50,
    date: "2023-08-05",
  },
  {
    storyId: "6",
    userId: "2",
    title: "The Haunted Mansion",
    body: "It was a dark and stormy night...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["horror", "mystery"],
    views: 6000,
    upvotes: 600,
    downvotes: 60,
    date: "2023-07-16",
  },
  {
    storyId: "7",
    userId: "2",
    title: "The Curse of the Ghost Ship",
    body: "Sailing on a moonless night...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["ghosts", "sea"],
    views: 7000,
    upvotes: 700,
    downvotes: 70,
    date: "2023-06-27",
  },
  {
    storyId: "8",
    userId: "2",
    title: "Whispers in the Dark",
    body: "In the depths of the forest...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["thriller", "mystery"],
    views: 8000,
    upvotes: 800,
    downvotes: 80,
    date: "2023-06-09",
  },
  {
    storyId: "9",
    userId: "3",
    title: "Echoes of Atlantis",
    body: "Beneath the waves...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["mythology", "adventure"],
    views: 9000,
    upvotes: 900,
    downvotes: 90,
    date: "2023-06-17",
  },
  {
    storyId: "10",
    userId: "3",
    title: "The Forbidden Temple",
    body: "Hidden in the jungle...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["adventure", "mystery"],
    views: 10000,
    upvotes: 1000,
    downvotes: 100,
    date: "2023-06-07",
  },
  {
    storyId: "11",
    userId: "4",
    title: "A Journey to Remember",
    body: "Across vast landscapes...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["journey", "adventure"],
    views: 11000,
    upvotes: 1100,
    downvotes: 110,
    date: "2023-08-19",
  },
  {
    storyId: "12",
    userId: "4",
    title: "Whispers of the Wind",
    body: "In the quiet meadows...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["nature", "poetry"],
    views: 12000,
    upvotes: 1200,
    downvotes: 120,
    date: "2023-06-03",
  },
  {
    storyId: "13",
    userId: "5",
    title: "Into the Unknown",
    body: "Stepping into the void...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["exploration", "mystery"],
    views: 13000,
    upvotes: 1300,
    downvotes: 130,
    date: "2023-06-18",
  },
  {
    storyId: "14",
    userId: "5",
    title: "The Last Stand",
    body: "Facing insurmountable odds...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["war", "drama"],
    views: 14000,
    upvotes: 1400,
    downvotes: 140,
    date: "2023-10-04",
  },
  {
    storyId: "15",
    userId: "5",
    title: "Dreams of Tomorrow",
    body: "In a world yet to be...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["future", "sci-fi"],
    views: 15000,
    upvotes: 1500,
    downvotes: 150,
    date: "2022-06-05",
  },
  {
    storyId: "16",
    userId: "5",
    title: "Shadows of the Past",
    body: "Haunted by memories...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["memory", "psychological"],
    views: 16000,
    upvotes: 1600,
    downvotes: 160,
    date: "2022-12-06",
  },
  {
    storyId: "17",
    userId: "5",
    title: "Serenade of the Night",
    body: "Under the starry sky...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["romance", "night"],
    views: 17000,
    upvotes: 1700,
    downvotes: 170,
    date: "2022-11-14",
  },
  {
    storyId: "18",
    userId: "5",
    title: "The Art of Silence",
    body: "In the tranquil moments...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["peace", "serenity"],
    views: 18000,
    upvotes: 1800,
    downvotes: 180,
    date: "2022-10-29",
  },
  {
    storyId: "19",
    userId: "5",
    title: "Whispers of the Forest",
    body: "Amidst the rustling leaves...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["nature", "whisper"],
    views: 19000,
    upvotes: 1900,
    downvotes: 190,
    date: "2023-09-10",
  },
  {
    storyId: "20",
    userId: "5",
    title: "Echoes of Eternity",
    body: "In the passage of time...Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, porro et reprehenderit molestias illum cum sapiente saepe voluptatum pariatur atque laudantium voluptatibus facilis veritatis asperiores qui minima unde eum sit reiciendis debitis vel aperiam veniam. Consequatur dolore ex id rem quis natus exercitationem, quae distinctio nisi necessitatibus ea pariatur praesentium!",
    tags: ["time", "eternity"],
    views: 20000,
    upvotes: 2000,
    downvotes: 200,
    date: "2023-08-05",
  },
];

const tags = [
  "fantasy",
  "adventure",
  "time-travel",
  "nature",
  "space",
  "sci-fi",
  "legend",
  "mythology",
  "horror",
  "ghosts",
  "sea",
  "thriller",
  "journey",
  "poetry",
  "exploration",
  "mystery",
  "war",
  "drama",
  "future",
  "memory",
  "psychological",
  "romance",
  "night",
  "peace",
  "serenity",
  "whisper",
  "time",
  "eternity",
];

const comments = [
  {
    commentId: "1",
    storyId: "1",
    userId: "2",
    text: "Wow, what an amazing story! I was completely captivated from start to finish.",
  },
  {
    commentId: "2",
    storyId: "1",
    userId: "3",
    text: "I agree! The way the author described the forest was so vivid and immersive.",
  },
  {
    commentId: "3",
    storyId: "1",
    userId: "4",
    text: "Absolutely breathtaking. I couldn't put it down until I reached the end.",
  },
  {
    commentId: "4",
    storyId: "6",
    userId: "1",
    text: "This story gave me chills! The haunted mansion was described in such detail, I felt like I was there.",
  },
  {
    commentId: "5",
    storyId: "6",
    userId: "3",
    text: "I had to read this with all the lights on! The atmosphere was so eerie and unsettling.",
  },
  {
    commentId: "6",
    storyId: "10",
    userId: "2",
    text: "The Forbidden Temple sounds like a thrilling adventure! I'd love to explore it myself.",
  },
  {
    commentId: "7",
    storyId: "8",
    userId: "4",
    text: "The suspense in 'Whispers in the Dark' kept me on the edge of my seat throughout the entire read.",
  },
  {
    commentId: "8",
    storyId: "13",
    userId: "1",
    text: "I can't stop thinking about 'Into the Unknown'. The mystery and sense of exploration are captivating!",
  },
  {
    commentId: "9",
    storyId: "15",
    userId: "3",
    text: "Dreams of Tomorrow paints such a vivid picture of a future world. It's both inspiring and thought-provoking.",
  },
  {
    commentId: "10",
    storyId: "17",
    userId: "2",
    text: "Serenade of the Night is a beautifully romantic tale under the starry sky. It made me long for such moments.",
  },
  {
    commentId: "11",
    storyId: "20",
    userId: "4",
    text: "Echoes of Eternity delves into profound themes of time and eternity. It left me pondering the nature of existence.",
  },
  {
    commentId: "12",
    storyId: "1",
    userId: "3",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "13",
    storyId: "12",
    userId: "3",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "14",
    storyId: "13",
    userId: "4",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "15",
    storyId: "14",
    userId: "1",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "16",
    storyId: "20",
    userId: "4",
    text: "Echoes of Eternity delves into profound themes of time and eternity. It left me pondering the nature of existence.",
  },
  {
    commentId: "17",
    storyId: "1",
    userId: "3",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "18",
    storyId: "12",
    userId: "3",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "19",
    storyId: "13",
    userId: "4",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
  {
    commentId: "20",
    storyId: "14",
    userId: "1",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda porro reiciendis rem sequi est, ducimus tempora repellat aperiam tempore adipisci.",
  },
];

module.exports = {
  users,
  stories,
  comments,
  tags,
};
